[versions]
kotlin = "2.0.21"
mokoResources = "0.24.4"

[plugins]
mokoResources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "mokoResources" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

[libraries]
mokoResources-core = { module = "dev.icerock.moko:resources", version.ref = "mokoResources" }